SELECT MIN(SR),CITY,MONTH_NAME FROM
(SELECT   CITY, MONTH_NAME,SALES, RANK() OVER(ORDER BY SALES,MONTH_NAME) AS SR
FROM DBO.TEST  GROUP BY CITY,MONTH_NAME,SALES)
S
GROUP BY CITY,MONTH_NAME
SELECT F.MONTH_NAME, S.CITY FROM
(select CITY,SALES,MONTH_NAME from dbo.test )S
INNER JOIN

(select max(sales) MS,month_name from dbo.test group by month_name) F
ON S.SALES = F.MS AND S.MONTH_NAME = F.MONTH_NAME

order by month_name
INSERT INTO DBO.TEST (SALES,MONTH_NAME,CITY) VALUES	(560,'202201','MUM')

SELECT MONTH_NAME,SUM(SALES)
     , sum(sum(SALES)) OVER (ORDER BY MONTH_NAME) AS running_sum,
	 sum(SALES) OVER (ORDER BY MONTH_NAME) AS running_sum
FROM   DBO.TEST
GROUP  BY MONTH_NAME,SALES
ORDER  BY date_trunc('month', date_added)