--FACT_ZERO_Enquiry_New_NW_MGNT
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(MONTH_NAME, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMM')) FROM RPT.[FACT_ZERO_Enquiry_New_NW_MGNT])
WHERE TABLE_NAME = 'RPT.FACT_ZERO_Enquiry_New_NW_MGNT'

--RPT.FACT_RETAIL_HCR_DEALER_NETWORK
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.FACT_RETAIL_HCR_DEALER_NETWORK)
WHERE TABLE_NAME = 'RPT.FACT_RETAIL_HCR_DEALER_NETWORK'

--RPT.FACT_RETAIL_ECR_DEALER_NETWORK  
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.FACT_RETAIL_ECR_DEALER_NETWORK)
WHERE TABLE_NAME = 'RPT.FACT_RETAIL_ECR_DEALER_NETWORK'                                                                

--RPT.FACT_RETAIL_NETWORK_DB_DC
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.FACT_RETAIL_NETWORK_DB_DC)
WHERE TABLE_NAME = 'RPT.FACT_RETAIL_NETWORK_DB_DC' 

--Enquiry_TYPE_NW_MGNT
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.Enquiry_TYPE_NW_MGNT)
WHERE TABLE_NAME = 'RPT.Enquiry_TYPE_NW_MGNT'

/*TM_Mapping
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.TM_Mapping)
WHERE TABLE_NAME = 'RPT.TM_Mapping'*/

--DEALERSHIP_ZERO_STOCK_AVAILABILITY
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.DEALERSHIP_ZERO_STOCK_AVAILABILITY)
WHERE TABLE_NAME = 'RPT.DEALERSHIP_ZERO_STOCK_AVAILABILITY'

--DEALERSHIP_STOCK_AVAILABILITY
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.DEALERSHIP_STOCK_AVAILABILITY)
WHERE TABLE_NAME = 'RPT.DEALERSHIP_STOCK_AVAILABILITY'

--EXCHANGE_PENETRATION_DETAIL
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.EXCHANGE_PENETRATION_DETAIL)
WHERE TABLE_NAME = 'RPT.EXCHANGE_PENETRATION_DETAIL'

--Enquiry_New
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.Enquiry_New)
WHERE TABLE_NAME = 'RPT.Enquiry_New'

--Enquiry_New_NW_MGNT
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.Enquiry_New_NW_MGNT)
WHERE TABLE_NAME = 'RPT.Enquiry_New_NW_MGNT'

/*
--[EMS_4.0]
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(MONTH_NAME, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMM')) FROM RPT.[EMS_4.0])
WHERE TABLE_NAME = 'RPT.[EMS_4.0]' */

--Enquiry_PEN
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.Enquiry_PEN)
WHERE TABLE_NAME = 'RPT.Enquiry_PEN'

--FACT_RETAIL_FINANCE_DEALER_NETWORK
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.FACT_RETAIL_FINANCE_DEALER_NETWORK)
WHERE TABLE_NAME = 'RPT.FACT_RETAIL_FINANCE_DEALER_NETWORK'

---FACT_ZERO_RETAIL_ECR
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(MONTH_NAME, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMM')) FROM RPT.FACT_ZERO_RETAIL_ECR)
WHERE TABLE_NAME = 'RPT.FACT_ZERO_RETAIL_ECR'

---FACT_BTL_CAMPAIGN_RETAIL
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.FACT_BTL_CAMPAIGN_RETAIL)
WHERE TABLE_NAME = 'RPT.FACT_BTL_CAMPAIGN_RETAIL'

---FACT_COUNTER_RETAIL
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.FACT_COUNTER_RETAIL)
WHERE TABLE_NAME = 'RPT.FACT_COUNTER_RETAIL'

---FACT_SALES_LEADS
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.FACT_SALES_LEADS)
WHERE TABLE_NAME = 'RPT.FACT_SALES_LEADS'

---VS_Vehicle_booking
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(DAY_DT, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMMdd')) FROM RPT.VS_Vehicle_booking)
WHERE TABLE_NAME = 'RPT.VS_Vehicle_booking'



---FACT_TEST_DRIVE_ENQUIRY
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(CAL_DATE, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMM')) FROM RPT.FACT_TEST_DRIVE_ENQUIRY)
WHERE TABLE_NAME = 'RPT.FACT_TEST_DRIVE_ENQUIRY
'

---FACT_ZERO_ENQUIRY
UPDATE [RPT].[CTRL_TABLE]
SET DATA_TILL = (SELECT MAX(FORMAT(  CONVERT(DATETIME, SWITCHOFFSET(MONTH_NAME, DATEPART(TZOFFSET, 
getdate() AT TIME ZONE 'India Standard Time'))), 'yyyyMM')) FROM RPT.[FACT_ZERO_ENQUIRY])
WHERE TABLE_NAME = 'RPT.FACT_ZERO_ENQUIRY'