CREATE TABLE RPT.FACT_SERVICE_WECONNECTED
WITH (DISTRIBUTION = ROUND_ROBIN,HEAP) AS

SELECT 
DEALER_CODE,
CALLING_TYPE,
MONTH_NAME,
SUM(CALLS_ATTEMPTED) AS CALLS_ATTEMPTED,
SUM(CALLS_ATTEMPTED_UNQ) AS CALLS_ATTEMPTED_UNQ,
SUM(CALLS_CONNECTED) AS CALLS_CONNECTED,
SUM(BOOKING_DONE) AS BOOKING_DONE,
SUM(TTL_TURNUP) AS TTL_TURNUP,
SUM(WRONG_NUMBER) AS WRONG_NUMBER,
SUM(DISTINCT FOLLOW_UPS) AS FOLLOW_UPS
FROM (
SELECT 
SUBSTRING(DH.ORGANIZATION_NAME,1,5) AS DEALER_CODE,
LD.NAME as CALLING_TYPE,
DD.X_MONTH_NAME AS MONTH_NAME,
COUNT(distinct WEF.ACTIVITY_WID) as CALLS_ATTEMPTED,
0 AS CALLS_ATTEMPTED_UNQ,
COUNT(distinct CASE WHEN WEF.X_CONTACT_STATUS = 'Contacted' then WEF.ACTIVITY_WID end ) as CALLS_CONNECTED,
0 AS BOOKING_DONE,
COUNT(distinct WEF.X_ORDER_WID) as TTL_TURNUP,
COUNT(distinct CASE WHEN WEF.X_CONTACT_STATUS = 'Wrong Number' then WEF.ACTIVITY_WID end ) as WRONG_NUMBER,
CASE WHEN WEF.NEXT_FOLLOW_DT IS NULL then 0 ELSE 1 END AS FOLLOW_UPS

FROM 
EDW_OLAPPRD.W_DAY_D DD  ,
EDW_OLAPPRD.WC_INT_ORG_DH DH  ,
EDW_OLAPPRD.W_INT_ORG_D ID  ,
EDW_OLAPPRD.W_LOV_D LD  ,
EDW_OLAPPRD.WC_WECONNECT_F WEF  
WHERE   DD.ROW_WID = WEF.ACTIVITY_CREATED_DT_WID 
AND LD.ROW_WID = WEF.X_SERVICE_TYPE_WID 
AND ID.INTEGRATION_ID = DH.DIVISION_ID
AND DD.FSCL_YEAR = 2023 
AND DD.X_MONTH_NAME = '2023 May' 
AND ID.ROW_WID = WEF.DEALER_WID 
AND DH.ORGANIZATION_NAME LIKE '1%'

GROUP BY 
DD.X_MONTH_NAME, 
LD.NAME, 
DH.ORGANIZATION_NAME, 
CASE WHEN WEF.NEXT_FOLLOW_DT IS NULL THEN 0 ELSE 1 END  
 
UNION
 
SELECT 
SUBSTRING(DH.ORGANIZATION_NAME,1,5) AS DEALER_CODE,
LD.NAME AS CALLING_TYPE,
DD.X_MONTH_NAME AS MONTH_NAME,
0 AS CALLS_ATTEMPTED,
COUNT(distinct WEF.ASSET_NUM) as CALLS_ATTEMPTED_UNQ,
0 AS CALLS_CONNECTED,
0 AS BOOKING_DONE,
0 AS TTL_TURNUP,
0 AS WRONG_NUMBER,
CASE WHEN WEF.NEXT_FOLLOW_DT IS NULL THEN 0 ELSE 1 END AS FOLLOW_UPS
FROM 
EDW_OLAPPRD.W_DAY_D DD  ,
EDW_OLAPPRD.WC_INT_ORG_DH DH  ,
EDW_OLAPPRD.W_INT_ORG_D ID  ,
EDW_OLAPPRD.W_LOV_D LD  ,
EDW_OLAPPRD.WC_WECONNECT_F WEF  
WHERE   DD.ROW_WID = WEF.ACTIVITY_CREATED_DT_WID 
AND LD.ROW_WID = WEF.X_SERVICE_TYPE_WID 
AND ID.INTEGRATION_ID = DH.DIVISION_ID 
AND DD.FSCL_YEAR = 2023 
AND DD.X_MONTH_NAME = '2023 May' 
AND ID.ROW_WID = WEF.DEALER_WID 
AND DH.ORGANIZATION_NAME LIKE '1%'
GROUP BY 
DD.X_MONTH_NAME, 
LD.NAME, 
DH.ORGANIZATION_NAME, 
CASE WHEN WEF.NEXT_FOLLOW_DT IS NULL THEN 0 ELSE 1 END 

UNION

SELECT
SUBSTRING(DH.ORGANIZATION_NAME,1,5) AS DEALER_CODE,
LD.NAME AS CALLING_TYPE,
DD.X_MONTH_NAME AS MONTH_NAME,
0 AS CALLS_ATTEMPTED,
0 AS CALLS_ATTEMPTED_UNQ,
0 AS CALLS_CONNECTED,
COUNT(DISTINCT WEF.SR_WID) as BOOKING_DONE,
0 AS TTL_TURNUP,
0 AS WRONG_NUMBER,
CASE WHEN WEF.NEXT_FOLLOW_DT IS NULL THEN 0 ELSE 1 END AS FOLLOW_UPS

FROM 
EDW_OLAPPRD.W_DAY_D DD  ,
EDW_OLAPPRD.WC_INT_ORG_DH DH  ,
EDW_OLAPPRD.W_INT_ORG_D ID  ,
EDW_OLAPPRD.W_LOV_D LD  ,
EDW_OLAPPRD.WC_WECONNECT_F WEF  
WHERE   DD.ROW_WID = WEF.ACTIVITY_CREATED_DT_WID 
AND LD.ROW_WID = WEF.X_SERVICE_TYPE_WID 
AND ID.INTEGRATION_ID = DH.DIVISION_ID
AND DD.FSCL_YEAR = 2023 
AND DD.X_MONTH_NAME = '2023 May' 
AND ID.ROW_WID = WEF.DEALER_WID
AND DH.ORGANIZATION_NAME LIKE '1%'
GROUP BY 
DH.ORGANIZATION_NAME,
LD.NAME, 
DD.X_MONTH_NAME,
CASE WHEN WEF.NEXT_FOLLOW_DT IS NULL THEN 0 ELSE 1 END ) WECON

GROUP BY
DEALER_CODE,
CALLING_TYPE,
MONTH_NAME